// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwAd4dms1Wpuv_uieMyVo4Bl3uRrp8GrA',
    appId: '1:1022568952358:web:3cfb1fe452f8765cf4ace7',
    messagingSenderId: '1022568952358',
    projectId: 'technical-test-74503',
    authDomain: 'technical-test-74503.firebaseapp.com',
    storageBucket: 'technical-test-74503.firebasestorage.app',
    measurementId: 'G-V3F1RGC6S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHS2gOrQR7dp8dx6ZjixZn9uItaI_51M',
    appId: '1:1022568952358:android:c539b506a6905342f4ace7',
    messagingSenderId: '1022568952358',
    projectId: 'technical-test-74503',
    storageBucket: 'technical-test-74503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaAkokUdgCbpVSIwOeMP6ML74lSQ6Vct4',
    appId: '1:1022568952358:ios:61708d87a5111721f4ace7',
    messagingSenderId: '1022568952358',
    projectId: 'technical-test-74503',
    storageBucket: 'technical-test-74503.firebasestorage.app',
    iosBundleId: 'com.example.technicalTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaAkokUdgCbpVSIwOeMP6ML74lSQ6Vct4',
    appId: '1:1022568952358:ios:61708d87a5111721f4ace7',
    messagingSenderId: '1022568952358',
    projectId: 'technical-test-74503',
    storageBucket: 'technical-test-74503.firebasestorage.app',
    iosBundleId: 'com.example.technicalTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwAd4dms1Wpuv_uieMyVo4Bl3uRrp8GrA',
    appId: '1:1022568952358:web:3222c4feb4b74427f4ace7',
    messagingSenderId: '1022568952358',
    projectId: 'technical-test-74503',
    authDomain: 'technical-test-74503.firebaseapp.com',
    storageBucket: 'technical-test-74503.firebasestorage.app',
    measurementId: 'G-KWEVT5EZZN',
  );

}